# Generated by Django 6.0.1 on 2026-01-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20260129_1238'),
    ]

    operations = [
    ]
