# Generated by Django 6.0.1 on 2026-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20260129_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the discussion', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time the AI summary was generated', null=True),
        ),
    ]
